### ISSUE TITLE
Exception: Failed to get file URL. File down or pattern changed

### ISSUE THREAD

**Issue by chickenstealers** [Sorrow446/ZS-DL#6]
I think the pattern has change on zippyshare

> URL 1 of 3:
> URL failed.
> Traceback (most recent call last):
>   File "zs-dl.py", line 183, in <module>
>     main(url)
>   File "zs-dl.py", line 150, in main
>     file_url, fname = extract(url, server, id)
>   File "zs-dl.py", line 106, in extract
>     raise Exception('Failed to get file URL. File down or pattern changed.')
> Exception: Failed to get file URL. File down or pattern changed.

can you check it?
Thanks

**Comment by chickenstealers** [comment]
Owh sorry, it's working fine
The file has been removed on zippyshare, so it generate error

Thanks
